### ISSUE TITLE
task tracker

### ISSUE THREAD

**Issue by DevinBayly** [DevinBayly/thermal_imaging#15]
- [ ] #16
- [ ] #21
- [ ] troubleshoot why the output serialized data is empty
- [ ] #20
- [ ] Finish reading article #11 
- [ ] finish reading article #10 
- [ ] Make python class diagram from sketch #13 such that inheriting allows for combinations of options outlined
- [x] #19
- [ ] Reach out to the data science ambassadors about who is the right person to talk with for CV expertise
- [ ] update diagram to include bgsegm options and how the blob analysis parameters can be tuned, also include the post processing step of removing the detection tracks that didn't start from rest, and include the csv export step
